### ISSUE TITLE
TYPO3 v12 single view error

### ISSUE THREAD

**Issue by sleepstorm** [Patta/tt_news#4]
Hi Pat,

I tested the latest version of tt_news v12 in two older TYPO3 11.5 websites, while upgrading to TYPO3 12.4. Installation of the extension works very well and after that the list views work like it should. But in both websites I get an error in the single view, looking like in the image below. To be sure it's not my in own theme I deactivated all my tt_news typoscript config and worked with only the page plug-ins, but the error persists. Here's a screenshot:

![image](https://github.com/Patta/tt_news/assets/132196662/f507fbf3-49f4-4d1e-a88c-32cb0358dbf5)

Thanks for the good work! I am already quite happy with this tt_news version ;-)

Best regards,
Michel Cerrone

**Comment by Patta** [comment]
Thanks, fixed with a883930

Please note that tt_news will probably not work correctly with the ^12.4 workspace extension and needs further testing and adjustments.

**Comment by sleepstorm** [comment]
Thank you! None of the sites I have with tt_news need Workspaces, so for me it's not a problem. I am so glad that I can continue with tt_news for now, appreciate your work a lot!
