### ISSUE TITLE
Error in Upgrade Wizard after upgrade to TYPO3 12

### ISSUE THREAD

**Issue by sleepstorm** [Patta/tt_news#5]
Hi Pat,

I had another multi-site multi-language TYPO3 instance where I did the switch to tt_news v12.x-dev during an upgrade to TYPO3 12 when I got an error that blocks the upgrade steps. The error looks like this:

![image](https://github.com/Patta/tt_news/assets/132196662/d9c0c500-cce7-47f7-8e4a-ec78722453d9)

It had a list of TYPO3 12 compatible extensions besides rupertgermann/tt_news:v12.x-dev:

- amazing/gh-randomcontent
- internetgalerie/ig-slug
- joppnet/jn_lighterbox
- in2code/powermail
- derhansen/sf_event_mgt
- sjbr/static-info-tables

In an attempt to get the upgrade done, I one by one composer removed all these extensions, but the error did not disappear. I even removed typo3/cms-webhooks and typo3/cms-workspaces. 

So I'm stuck with this one for now.

**Comment by Patta** [comment]
@sleepstorm thanks for your issue. I will check and fix asap. 
In the meanwhile try to replace fetchColumn with fetchOne, see also  https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96287-DoctrineDBALv3.html

**Comment by Patta** [comment]
fixed with 2498a4db3ced800822452f135a570f15ef31a7c7

**Comment by sleepstorm** [comment]
Hi @Pat, I tested your fix yesterday and it worked, so I am very happy. Thanks a lot!
